### ISSUE TITLE
Undefined name in Ruff:  F821

### ISSUE THREAD

**Issue by krzysztofrusek** [patrick-kidger/jaxtyping#162]
I the following code ruff 0.1.14 complains abut dimension annotation.

```python
class VariationalInferenceThompsonSampling(AbstractAgent):
    mcs: Int[Array, "n"]
    tx_power: Float[Array, " n"]
```

For `mcs` I got error Undefined name `n` Ruff F821
It looks like adding a space at the beginning solve this, but I am not sure is this is correct.

**Comment by patrick-kidger** [comment]
See [this FAQ entry](https://docs.kidger.site/jaxtyping/faq/#flake8-or-ruff-are-throwing-an-error).

**Comment by krzysztofrusek** [comment]
O... thank you for pointing this.
