### ISSUE TITLE
Annotations for tensors with dynamics dimensions

### ISSUE THREAD

**Issue by martenlienen** [patrick-kidger/jaxtyping#225]
Hi,
what would be the idiomatic way to describe the return shape of, for example, `torch.zeros` in jaxtyping?

```python
def zeros(size: tuple[int, ...]) -> Float[Tensor, "what do I put here?"]:
    pass
```

How can I encode that the output shape is determined by the number of elements of the `size` tuple?

**Comment by patrick-kidger** [comment]
Hey there! Unfortunately this isn't supported -- it'd require a fairly tricky rewrite of some internals: https://github.com/patrick-kidger/jaxtyping/pull/140#issuecomment-1804886283

**Comment by martenlienen** [comment]
Thanks for clearing that up!
