### ISSUE TITLE
Is it possible to use `AbstractDtype` to support syntax of not `Float[Array, "dim1 dim2"]` but instead `FloatArr["dim1 dim2"]`?

### ISSUE THREAD

**Issue by stu-twelvelabs** [patrick-kidger/jaxtyping#238]
Hi, great project 🙏. I often find myself not caring a lot about dimensions but not too too much about the dtype itself. I am curious: is there a way to create a Dtype that would support annotation of the form `def blah(x: Arr["batch z"]) -> ...:` rather than requiring a concrete Dtype as the first arg? For whatever reason my eyes also favor `FloatArr[...]` to `Float[Array, ...`.

Thank you!

**Comment by patrick-kidger** [comment]
Yes if you don't want static type checking:
```python
class FloatArr:
    def __class_getitem__(cls, item):
        return Float[Array, item]
```

But unfortunately this syntax is not compatible with pyright/mypy/etc. For these you will need to use `Float[Array, ...]`. (Compatibility with such tools is the reason this syntax is what it is.)
