### ISSUE TITLE
AbstractDType Example

### ISSUE THREAD

**Issue by srush** [patrick-kidger/jaxtyping#239]
Runing with 0.2.33 . I was trying out the new AbstractDtype. I tried this example code 

However I get the error: `Expected no type arguments for class "FooDtype"` on the function f

Am I doing something wrong?

```python

import jaxtyping
from jaxtyping import AbstractDtype

class FooDtype(AbstractDtype):
    dtypes = ["foo"]

class MyArray:
    @property
    def dtype(self) -> str:
        return "foo"
    
    @property
    def shape(self) -> Tuple[int, ...]:
        return (3, 1, 4)
    
    def pizza(self) -> None:
        print("x")
        return

def f(x: FooDtype[MyArray, "3 1 4"]) -> None:
    x.pizza()
    return None
```

**Comment by srush** [comment]
The following seems to work. A bit hacky but I think it fixes my issue. Is this the intended thing to do?

```python
if TYPE_CHECKING:
    from typing import Annotated as FooDtype # noqa: F401
    
else:
    class FooDtype(AbstractDtype):
        dtypes = ["foo"]


class MyArray:
    @property
    def dtype(self) -> str:
        return "foo"
    
    @property
    def shape(self) -> Tuple[int, ...]:
        return (3, 1, 4)
    
    def pizza(self) -> None:
        print("x")
        return

def f(x: FooDtype[MyArray, "3 1 4"]) -> None:
    x.pizza()
    return None
```

**Comment by patrick-kidger** [comment]
To be clear, you mean that you get this error from a static type checker? (pyright / mypy / ...)

Indeed, the `from typing import Annotated as FooDtype` is the appropriate fix here. As you may have gleaned this is what jaxtyping does internally as well. Generally speaking this is a great trick for attaching metadata to a type in a way that is compatible with static type checking.

**Comment by srush** [comment]
Yup, static checker. 

Closing, but maybe can add to the docs examples? Everything else in the docs works with static checkers too.

**Comment by patrick-kidger** [comment]
Makes sense! I'd be happy to take a PR on this :)
