### ISSUE TITLE
Is there a way to temporarily disable runtime typechecking?

### ISSUE THREAD

**Issue by kho** [patrick-kidger/jaxtyping#247]
Hi! I am working on a codebase with lots of functions decorated with `jaxtyping.jaxtyped(typechecker=typeguard.typechecked)`. Every now and then, we wish to disable runtime typechecking entirely (for example when using jax2tf with polymorphic shapes). Newer versions of typeguard has `suppress_type_checks` which might be allow us to do that but it appears jaxtyping requires typeguard 2. Is there a way I can achieve the same thing with jaxtyping?

**Comment by patrick-kidger** [comment]
Yes, set `JAXTYPING_DISABLE=1`:

https://github.com/patrick-kidger/jaxtyping/blob/f4ca4c98fecf9bf1d85c727e40bf1630a190a70f/jaxtyping/_config.py#L21

(I don't think this is documented yet though!)

**Comment by kho** [comment]
Thanks! Worked like a charm!
