### ISSUE TITLE
Question - Is `jitkwargs` part of the public API?

### ISSUE THREAD

**Issue by jeertmans** [patrick-kidger/jaxtyping#248]
Hello!

Reading your documentation, I see no reference to some of the `jax.jit` keyword arguments, e.g., `inline`.
However, in your code, the `equinox.filter_jit` exposes the `**jitkwargs` arguments, so I guess I could toggle inlining with `equinox.filter_jit(inline=True)`.

However, as you explicitly removed this argument from the docstring, with `@doc_remove_args`, I was wondering if it was considered to be part of the public API? My question is to avoid possible breaking changes in my code :-)

Thanks!

https://github.com/patrick-kidger/equinox/blob/14e2c49d59a0c7e41f04caec82c84b95389a6b10/equinox/_jit.py#L282-L290

**Comment by patrick-kidger** [comment]
It is not part of the public API. Generally I didn't want people thinking of the kwargs that `jax.jit` accepts, since we override so many of them ourselves anyway.

That said, I'm unlikely to ever remote this... so I think go for it :)

**Comment by jeertmans** [comment]
Thanks for your reply :)

I understand that exposing all jit kwargs makes little sense as you perform custom surgery to automatically handle static args, etc., but I think some arguments like inlining should never conflict with this library, so I could also be safe to expose them :)

But I am fine with passing them as kwargs, even if their are not officially part of your API.
