### ISSUE TITLE
'jax' dependency is missing in pyproject.toml

### ISSUE THREAD

**Issue by yurivict** [patrick-kidger/jaxtyping#250]
There are import statements in the code like this: ```from jax import```.
But 'jax' isn't listed as a dependency.

**Comment by patrick-kidger** [comment]
JAX is intentionally not a dependency, as `jaxtyping` is also used to add shape/dtype annotations to PyTorch etc.

(At this point the 'jax' in 'jaxtyping' is historical, really.)

**Comment by yurivict** [comment]
Thanks!
