### ISSUE TITLE
PRNGKeyArray doesn't support new (experimental) RBG PRNG impl

### ISSUE THREAD

**Issue by csuter** [patrick-kidger/jaxtyping#252]
When `jax.config.update('jax_default_prng_impl', 'unsafe_rbg')`, the value returned by jax.random.key(N) will (effectively) be a `UInt32[4]` (it's actually a scalar-shaped array with `dtype("<urbg>")`). This causes type errors when annotating PRNG key object with jt.PRNGKeyArray, which expects only scalar u32 or u32[2].

Here's a colab showing the jax behavior with unsafe_rbg: https://colab.research.google.com/drive/1FQtKBC8jCj2f8s3uABhFPuDjlI3Kz2AC?authuser=0#scrollTo=JU9QzhSxQN7T

c.f. also
 - [jax docs](https://jax.readthedocs.io/en/latest/jax.random.html#advanced-rng-configuration)
 - [xla docs](https://openxla.org/xla/operation_semantics#rngbitgenerator)

I think the fix would simply be adding another union to the current PRNGKeyArray definition covering the new case. Happy to send a PR if that's welcome.

**Comment by patrick-kidger** [comment]
Hmm, this works for me:
```python
from typing import get_args

import jax
import jax.random as jr
from jaxtyping import Array, Key, PRNGKeyArray


jax.config.update('jax_default_prng_impl', 'unsafe_rbg')

x = jr.key(0)

print(isinstance(x, get_args(PRNGKeyArray)))  # True
print(isinstance(x, Key[Array, ""]))  # True
```

This is using JAX 0.4.33 and jaxtyping 0.2.34.

**Comment by csuter** [comment]
I'm going to close this for now, to keep the tracker tidy, under the assumption that I was doing something silly. I'll update here if I learn anything helpful!
