### ISSUE TITLE
Failing CI builds

### ISSUE THREAD

**Issue by baluyotraf** [patrick-kidger/jaxtyping#272]
Hello! I saw that the CI to push the code to pypi is failing. I think it might be related to this? https://github.com/pypa/gh-action-pypi-publish/issues/290

Though the fix I think needs to be applied to https://github.com/patrick-kidger/action_update_python_project instead.

**Comment by patrick-kidger** [comment]
Thanks for the heads-up! Looks like a transitory GitHub failure, so I've just done a manual push to PyPI for the latest release instead :)

**Comment by baluyotraf** [comment]
Nah. Thank you for being quick to fix it. Really appreciate it.
