### ISSUE TITLE
Question about Array

### ISSUE THREAD

**Issue by carlosal1015** [patrick-kidger/jaxtyping#280]
Hi, many thanks for nice package. I have a question.

Suppose that `python-numpy` is installed, but not `python-jax`. See https://aur.archlinux.org/packages/python-jaxtyping#comment-908221

```python
import numpy as np
from jaxtyping import Array, Float
```

I see that

- `Array` point to `Array` class in `/usr/lib/python3.13/site-packages/jax/_src/basearray.py`.
- `Float` point to `Annotated` function in `/usr/lib/python3.13/typing.py`.

Therefore, is not possible use `Array` for typing numpy arrays. Is this intended behavior?

**Comment by johannahaffner** [comment]
Yes, it is the intended behaviour, documented [here](https://docs.kidger.site/jaxtyping/api/array/#array). 
Instead of the JAX-specific `Array`, you can also use `np.ndarray`, `torch.Tensor` and `tf.Tensor`.

**Comment by carlosal1015** [comment]
Many thanks 😄
